services:
  stock_autotrade:
    image: stock_autotrade:latest
    volumes:
      - ../:/home/kujira/workspace/stock_autotrade
    tty: true
    stdin_open: true
    network_mode: 'host'
    working_dir: /home/kujira/workspace/stock_autotrade
    command: [ "bash" ]
