services:
  ml-env:
    image: python-workspace-template:latest
    volumes:
      - ../../../:/home/kujira/workspace
    tty: true
    stdin_open: true
    network_mode: 'host'
    working_dir: /home/kujira/workspace/python-workspace-template
    command: ["bash"]
